package testgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/nasraldin/camunda-lab/internal/bpmn"
)

// Options controls generation.
type Options struct {
	OutDir string
	Lang   string // java|js
	Force  bool
}

// Generate writes test skeletons for a BPMN model.
func Generate(m bpmn.Model, opts Options) ([]string, error) {
	if opts.OutDir == "" {
		opts.OutDir = "tests"
	}
	if opts.Lang == "" {
		opts.Lang = "java"
	}
	switch opts.Lang {
	case "java":
		return generateJava(m, opts)
	case "js":
		return generateJS(m, opts)
	default:
		return nil, fmt.Errorf("unsupported lang %q (java|js)", opts.Lang)
	}
}

func generateJava(m bpmn.Model, opts Options) ([]string, error) {
	dir := filepath.Join(opts.OutDir, "java")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	class := sanitizeIdent(m.ProcessID) + "ProcessTest"
	path := filepath.Join(dir, class+".java")
	if err := checkOverwrite(path, opts.Force); err != nil {
		return nil, err
	}
	var jobs []string
	for _, e := range m.ServiceTasks() {
		if e.JobType != "" {
			jobs = append(jobs, e.JobType)
		}
	}
	data := map[string]any{
		"Class":     class,
		"ProcessID": m.ProcessID,
		"Jobs":      jobs,
	}
	tmpl := template.Must(template.New("java").Parse(javaTmpl))
	f, err := os.Create(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	if err := tmpl.Execute(f, data); err != nil {
		return nil, err
	}
	return []string{path}, nil
}

func generateJS(m bpmn.Model, opts Options) ([]string, error) {
	dir := filepath.Join(opts.OutDir, "js")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	path := filepath.Join(dir, sanitizeIdent(m.ProcessID)+".test.js")
	if err := checkOverwrite(path, opts.Force); err != nil {
		return nil, err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by camunda test generate — TODO assertions\n")
	fmt.Fprintf(&b, "describe(%q, () => {\n", m.ProcessID)
	for _, e := range m.ServiceTasks() {
		jt := e.JobType
		if jt == "" {
			jt = e.ID
		}
		fmt.Fprintf(&b, "  it.todo('worker handles job type %s');\n", jt)
	}
	if len(m.ServiceTasks()) == 0 {
		b.WriteString("  it.todo('cover happy path');\n")
	}
	b.WriteString("});\n")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	return []string{path}, nil
}

func checkOverwrite(path string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("%s exists (use --force)", path)
	}
	return nil
}

func sanitizeIdent(s string) string {
	if s == "" {
		return "Process"
	}
	var b strings.Builder
	for i, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteByte('P')
			}
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
	}
	out := b.String()
	if out == "" {
		return "Process"
	}
	return strings.ToUpper(out[:1]) + out[1:]
}

const javaTmpl = `// Generated by camunda test generate — skeleton only
// TODO: wire Camunda Process Test dependencies and assertions

class {{.Class}} {
  // processId = "{{.ProcessID}}"
  // @CamundaSpringProcessTest
{{range .Jobs}}  // job type: {{.}}
{{end}}
  void happyPath() {
    // TODO deploy + create instance for {{.ProcessID}}
  }
}
`
