package testgen

import (
	"fmt"
	"strings"

	"github.com/nasraldin/camunda-lab/internal/bpmn"
)

func renderJava(process bpmn.Process) (Artifact, error) {
	className := sanitizeIdent(process.ID) + "Test"
	path := "java/" + className + ".java"
	var source strings.Builder
	source.WriteString("// Generated by camunda-lab for process ")
	source.WriteString(javaString(process.ID))
	source.WriteString(".\n")
	source.WriteString("// JUnit 5 scaffold. TODO: add Camunda Process Test dependencies and replace limitations below.\n\n")
	source.WriteString("import org.junit.jupiter.api.Disabled;\n")
	source.WriteString("import org.junit.jupiter.api.Test;\n\n")
	source.WriteString("class ")
	source.WriteString(className)
	source.WriteString(" {\n")
	fmt.Fprintf(&source, "  static final String PROCESS_ID = %s;\n\n", javaString(process.ID))
	source.WriteString("  @Test\n")
	source.WriteString("  @Disabled(\"TODO: configure an isolated Camunda process-test runtime\")\n")
	source.WriteString("  void completesHappyPath() {\n")
	source.WriteString("    // TODO: deploy the BPMN resource, start PROCESS_ID, and assert the completed path.\n")
	source.WriteString("    // Limitation: generated tests never connect to or execute against a live cluster.\n")
	source.WriteString("    throw new UnsupportedOperationException(\"TODO scaffold must remain disabled until configured\");\n")
	source.WriteString("  }\n")
	for _, jobType := range uniqueJobTypes(process) {
		fmt.Fprintf(&source, "\n  // Job type %s\n", javaString(jobType))
		source.WriteString("  @Test\n")
		source.WriteString("  @Disabled(\"TODO: configure an isolated Camunda job-worker fixture\")\n")
		fmt.Fprintf(&source, "  void handles_%s() {\n", javaMethodIdent(jobType))
		source.WriteString("    // TODO: activate the job in an embedded/test runtime and assert variables and completion.\n")
		source.WriteString("    throw new UnsupportedOperationException(\"TODO scaffold must remain disabled until configured\");\n")
		source.WriteString("  }\n")
	}
	source.WriteString("}\n")
	return Artifact{Path: path, MediaType: "text/x-java-source", Content: []byte(source.String())}, nil
}

func javaMethodIdent(value string) string {
	return strings.ToLower(sanitizeIdent(value))
}

func javaString(value string) string {
	return fmt.Sprintf("%q", value)
}
